# Generated by Django 4.2 on 2023-05-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("decs", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=200)),
                ("summry", models.TextField()),
            ],
        ),
    ]
